### ISSUE TITLE
www A record

### ISSUE THREAD

**Issue by xanderificnl** [vnglst/koenvangilst.nl#124]
Hi Koen,

The link on your GitHub profile (not this repository) doesn't seem to work. This is likely due to a small oversight in DNS configuration, i.e. `www.koenvangilst.nl` doesn't resolve whereas `koenvangilst.nl` does. I figured you might appreciate a note. 

In the end, I found the live cursors post and I thoroughly enjoyed reading it. Thanks for that!

**Comment by vnglst** [comment]
Hi Xander, thanks for letting me know! I quickly fixed it. Really glad you liked my post about the live cursors.

**Comment by xanderificnl** [comment]
You're welcome! 

Fijne dag!
